"""corrigir_colunas_duplicadas_plano_alimentar

Revision ID: 9171f08061c1
Revises: c8188a37edc6
Create Date: 2025-06-14 14:31:04.300463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9171f08061c1'
down_revision: Union[str, None] = 'c8188a37edc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
