"""Adicionado Plano Alimentar

Revision ID: c8188a37edc6
Revises: d293d49e5583
Create Date: 2025-06-14 14:24:19.463022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8188a37edc6'
down_revision: Union[str, None] = 'd293d49e5583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Comandos corrigidos manualmente ###
    op.create_table('planos_alimentares',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tmb', sa.Float(), nullable=False),
        sa.Column('calorias_objetivo', sa.Float(), nullable=False),
        sa.Column('proteinas_g', sa.Float(), nullable=False),
        sa.Column('carboidratos_g', sa.Float(), nullable=False),
        sa.Column('gorduras_g', sa.Float(), nullable=False),
        sa.Column('data_criacao', sa.Date(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('usuario_id') # Garante que cada usuário tenha apenas um plano
    )
    op.create_index(op.f('ix_planos_alimentares_id'), 'planos_alimentares', ['id'], unique=False)
    op.create_index(op.f('ix_planos_alimentares_usuario_id'), 'planos_alimentares', ['usuario_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planos_alimentares_usuario_id'), table_name='planos_alimentares')
    op.drop_index(op.f('ix_planos_alimentares_id'), table_name='planos_alimentares')
    op.drop_table('planos_alimentares')
    # ### end Alembic commands ###
