"""Adiciona modelos de refeicao, treino e exercicio

Revision ID: 2ef6efe9f0a6
Revises: 9171f08061c1
Create Date: 2025-06-22 13:49:21.020816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef6efe9f0a6'
down_revision: Union[str, None] = '9171f08061c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo_muscular', sa.Enum('PEITO', 'COSTAS', 'PERNAS', 'BICEPS', 'TRICEPS', 'OMBROS', 'ABDOMEN', 'OUTRO', name='grupomuscularenum'), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercicios_id'), 'exercicios', ['id'], unique=False)
    op.create_index(op.f('ix_exercicios_nome'), 'exercicios', ['nome'], unique=True)
    op.create_table('treinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treinos_id'), 'treinos', ['id'], unique=False)
    op.create_index(op.f('ix_treinos_nome'), 'treinos', ['nome'], unique=False)
    op.create_table('itens_treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.String(), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_treino_id'), 'itens_treino', ['id'], unique=False)
    op.add_column('alimentos', sa.Column('calorias_por_100g', sa.Float(), nullable=False))
    op.add_column('alimentos', sa.Column('proteinas_por_100g', sa.Float(), nullable=True))
    op.add_column('alimentos', sa.Column('carboidratos_por_100g', sa.Float(), nullable=True))
    op.add_column('alimentos', sa.Column('gorduras_por_100g', sa.Float(), nullable=True))
    op.drop_column('alimentos', 'gorduras_g')
    op.drop_column('alimentos', 'porcao_gramas')
    op.drop_column('alimentos', 'carboidratos_g')
    op.drop_column('alimentos', 'calorias_por_porcao')
    op.drop_column('alimentos', 'proteinas_g')
    op.add_column('itens_refeicao', sa.Column('quantidade_gramas', sa.Float(), nullable=False))
    op.drop_column('itens_refeicao', 'quantidade')
    op.drop_constraint('planos_alimentares_usuario_id_key', 'planos_alimentares', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('planos_alimentares_usuario_id_key', 'planos_alimentares', ['usuario_id'], postgresql_nulls_not_distinct=False)
    op.add_column('itens_refeicao', sa.Column('quantidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('itens_refeicao', 'quantidade_gramas')
    op.add_column('alimentos', sa.Column('proteinas_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('alimentos', sa.Column('calorias_por_porcao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('alimentos', sa.Column('carboidratos_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('alimentos', sa.Column('porcao_gramas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('alimentos', sa.Column('gorduras_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('alimentos', 'gorduras_por_100g')
    op.drop_column('alimentos', 'carboidratos_por_100g')
    op.drop_column('alimentos', 'proteinas_por_100g')
    op.drop_column('alimentos', 'calorias_por_100g')
    op.drop_index(op.f('ix_itens_treino_id'), table_name='itens_treino')
    op.drop_table('itens_treino')
    op.drop_index(op.f('ix_treinos_nome'), table_name='treinos')
    op.drop_index(op.f('ix_treinos_id'), table_name='treinos')
    op.drop_table('treinos')
    op.drop_index(op.f('ix_exercicios_nome'), table_name='exercicios')
    op.drop_index(op.f('ix_exercicios_id'), table_name='exercicios')
    op.drop_table('exercicios')
    # ### end Alembic commands ###
