"""adicionar_campo_is_admin_ao_usuario

Revision ID: d293d49e5583
Revises: a5c35be478ca
Create Date: 2025-06-14 13:02:58.000843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd293d49e5583'
down_revision: Union[str, None] = 'a5c35be478ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alimentos_id'), 'alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_itens_refeicao_id'), 'itens_refeicao', ['id'], unique=False)
    op.create_index(op.f('ix_refeicoes_id'), 'refeicoes', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_column('usuarios', 'is_admin')
    op.drop_index(op.f('ix_refeicoes_id'), table_name='refeicoes')
    op.drop_index(op.f('ix_itens_refeicao_id'), table_name='itens_refeicao')
    op.drop_index(op.f('ix_alimentos_id'), table_name='alimentos')
    # ### end Alembic commands ###
